services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Duka_app
    restart: unless-stopped
    env_file:
      - .env       # ✅ Pulls all your APP_KEY, DB_PASS, etc. securely
    ports:
      - "${APP_PORT}:80"
      #- "443:443"
    volumes:
      - .:/var/www/html:cached          # Sync your project folder
      #- /etc/letsencrypt:/etc/letsencrypt:ro
      # Map your host certificates to the internal path we set in Dockerfile
      #- /etc/letsencrypt/live/mezgebedirijit.com/fullchain.pem:/etc/apache2/ssl/fullchain.pem:ro
      #- /etc/letsencrypt/live/mezgebedirijit.com/privkey.pem:/etc/apache2/ssl/privkey.pem:ro

     # Named Volumes to protect container-built dependencies
      - vendor_data:/var/www/html/vendor
      - node_data:/var/www/html/node_modules
      - storage_data:/var/www/html/storage
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: Duka_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3309:3306"    # ✅ Security: Only allows YOU (via SSH/Local)
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  vendor_data:
  node_data:
  storage_data:

